  - name: Copy files to Apache
    copy:
      src: /home/jcubillos555/index.php
      dest: /var/www/html
  - name: Copy files to Apache
    copy:
      src: /home/jcubillos555/insert.php
      dest: /var/www/html
  - name: Copy files to Apache
    copy:
      src: /home/jcubillos555/db_connection.php
      dest: /var/www/html         
  - name: Copy files to Apache
    copy:
      src: /home/jcubillos555/delete.php
      dest: /var/www/html
  - name: Copy files to Apache
    copy:
      src: /home/jcubillos555/update.php
      dest: /var/www/html
  - name: Copy files to Apache
    copy:
      src: /home/jcubillos555/style.css
      dest: /var/www/html           