# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- pac

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy Infra
  displayName: Deploy Infra Ansible
  jobs:
  - job: DeployInfraAnsible 
    displayName: DeployInfraAnsibleARM
    steps:
      - task: replacetokens@3
        inputs:
          rootDirectory: 'InfraAnsible'
          targetFiles: '**/*.yml'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '__'
          tokenSuffix: '__'