#Deploy Infraestructura base
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
      rgr: __rgr__
      vmnameansible: __vmnameansible__
      vmnamelab07: __vmnamelab07__
      vmname2lab07: __vmname2lab07__
      vmnamebdlab07: __vmnamebdlab07__
      dnsansiblelab07: __dnsansiblelab07__
      dnsweblab07: __dnsweblab07__
      dnsweb2lab07: __dnsweb2lab07__
      dnsbdlab07: __dnsbdlab07__
      userlab07: __userlab07__
      sizevmlab07: __sizevmlab07__
      offerlab07: __offerlab07__
      publisherlab0: __publisherlab0__
      skulab07: __skulab07__
      tagansiblelab07: __tagansiblelab07__
      tagweblab07: __tagweblab07__
      tagbdlab07: __tagbdlab07__
      virtualnetworklab07: __virtualnetworklab07__
      subnetlab07: __subnetlab07__
      nsglab07: __nsglab07__
      locationlab07: __locationlab07__
      autenthicationmethod: __autenthicationmethod__
      llavepublicalab07: __llavepublicalab07__
      #llavepublicalab07: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOcUiCw6qYodwRT6FcabSr6BF+UJQ5WCvOz4v9wulxV2Z9aDmKBMTKM0537n2umdY3++gMLjOEEuG4RYhuH1rX5mdDQvm5FP+bkfrXBUHTntJk1C91/FOvL6LpLoqKf5eZ01hFPzm2F+SdGdRXTWhDLOfyGF/kQNwpE+wrPRCdfpRU0FORA/q49OvfugorYXcYvMnvByftDzZVxiBQ+3c7bQR13ZhizM7pPAgGmBivpPT27XPkBViSFDVAR7CD6KD1r1BalyEgRNadWNp/BBFo9dAZwWd6tBwPC6ONgoF5qyvbot6rNZ+mprldb4DL4ZGpT8YFpoV2c+aPI8jnreCj jcubillos555@ansiblelab07

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ rgr }}"
      location: "{{ locationlab07 }}"

  - name: Deploy VM Ansible
    azure_rm_deployment:
      resource_group: "{{ rgr }}"
      name: Deploylab07
      parameters:
        vmName:
          value: "{{ vmnameansible }}"
        adminUsername:
          value: "{{ userlab07 }}"
        authenticationType:
          value: password
        adminPasswordOrKey:
          value: Proviteq.1999
        ubuntuOSVersion:
          value: "{{ skulab07 }}"
        location:
           value: "{{ locationlab07 }}"
        vmSize:
          value: "{{ sizevmlab07 }}"
        virtualNetworkName:
          value: "{{ virtualnetworklab07 }}"
        subnetName:
          value: "{{ subnetlab07 }}"   
        networkSecurityGroupName:
          value: "{{ nsglab07 }}" 
        dnsLabelPrefix:
          value: "{{ dnsansiblelab07 }}"
      template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
    register: azure

  - name: Tags VM
    azure_rm_virtualmachine:
      resource_group: "{{ rgr }}"
      name: "{{ vmnameansible }}"
      append_tags: True
      tags:
        env: "{{ tagansiblelab07 }}" 

  - name: VMExtension Install Ansible
    azure_rm_virtualmachineextension:
      name: myvmextension
      location: "{{ locationlab07 }}"
      resource_group: "{{ rgr }}"
      virtual_machine_name: "{{ vmnameansible }}"
      publisher: Microsoft.OSTCExtensions
      virtual_machine_extension_type: CustomScriptForLinux
      type_handler_version: "1.4"
      settings:
        {
            "fileUris":[ "https://raw.githubusercontent.com/Microsoft/azuredevopslabs/master/labs/vstsextend/ansible/armtemplate/install_ansible.sh"],
            "commandToExecute": "sh install_ansible.sh"
       }
      auto_upgrade_minor_version: true

  - name: VMExtension Permisos Ansible
    azure_rm_virtualmachineextension:
      name: myvmextension
      location: "{{ locationlab07 }}"
      resource_group: "{{ rgr }}"
      virtual_machine_name: "{{ vmnameansible }}"
      publisher: Microsoft.OSTCExtensions
      virtual_machine_extension_type: CustomScriptForLinux
      type_handler_version: "1.4"
      settings:
        {
            "fileUris":[ "https://sclab07.blob.core.windows.net/ansiblepermisos/ansiblepermisos.sh"],
            "commandToExecute": "sh ansiblepermisos.sh"
       }
      auto_upgrade_minor_version: true

  - name: Deploy VM Azure Apache1
    azure_rm_deployment:
      resource_group: "{{ rgr }}"
      name: Deploylab07
      parameters:
        vmName:
          value: "{{ vmnamelab07 }}"
        adminUsername:
          value: "{{ userlab07 }}"
        authenticationType:
          value: "{{ autenthicationmethod }}"
        adminPasswordOrKey:
          value: "{{ llavepublicalab07 }}"
        ubuntuOSVersion:
          value: "{{ skulab07 }}"
        location:
           value: "{{ locationlab07 }}"
        vmSize:
          value: "{{ sizevmlab07 }}"
        virtualNetworkName:
          value: "{{ virtualnetworklab07 }}"
        subnetName:
          value: "{{ subnetlab07 }}"   
        networkSecurityGroupName:
          value: "{{ nsglab07 }}" 
        dnsLabelPrefix:
          value: "{{ dnsweblab07 }}"
      template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
    register: azure

  - name: Tags VM Apache
    azure_rm_virtualmachine:
      resource_group: "{{ rgr }}"
      name: "{{ vmnamelab07 }}"
      append_tags: True
      tags:
        env: "{{ tagweblab07 }}" 

  - name: Deploy VM Azure Apache2 Prueba Inventario Dinamico
    azure_rm_deployment:
      resource_group: "{{ rgr }}"
      name: Deploylab07
      parameters:
        vmName:
          value: "{{ vmname2lab07 }}"
        adminUsername:
          value: "{{ userlab07 }}"
        authenticationType:
          value: "{{ autenthicationmethod }}"
        adminPasswordOrKey:
          value: "{{ llavepublicalab07 }}"
        ubuntuOSVersion:
          value: "{{ skulab07 }}"
        location:
           value: "{{ locationlab07 }}"
        vmSize:
          value: "{{ sizevmlab07 }}"
        virtualNetworkName:
          value: "{{ virtualnetworklab07 }}"
        subnetName:
          value: "{{ subnetlab07 }}"   
        networkSecurityGroupName:
          value: "{{ nsglab07 }}" 
        dnsLabelPrefix:
          value: "{{ dnsweb2lab07 }}"
      template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
    register: azure

  - name: Tags VM Apache
    azure_rm_virtualmachine:
      resource_group: "{{ rgr }}"
      name: "{{ vmname2lab07 }}"
      append_tags: True
      tags:
        env: "{{ tagweblab07 }}" 

  - name: Deploy VM Azure Mysql
    azure_rm_deployment:
      resource_group: "{{ rgr }}"
      name: Deploylab07
      parameters:
        vmName:
          value: "{{ vmnamebdlab07 }}"
        adminUsername:
          value: "{{ userlab07 }}"
        authenticationType:
          value: "{{ autenthicationmethod }}"
        adminPasswordOrKey:
          value: "{{ llavepublicalab07 }}"
        ubuntuOSVersion:
          value: "{{ skulab07 }}"
        location:
           value: "{{ locationlab07 }}"
        vmSize:
          value: "{{ sizevmlab07 }}"
        virtualNetworkName:
          value: "{{ virtualnetworklab07 }}"
        subnetName:
          value: "{{ subnetlab07 }}"   
        networkSecurityGroupName:
          value: "{{ nsglab07 }}" 
        dnsLabelPrefix:
          value: "{{ dnsbdlab07 }}"
      template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
    register: azure

  - name: Tags VM Base de Datos
    azure_rm_virtualmachine:
      resource_group: "{{ rgr }}"
      name: "{{ vmnamebdlab07 }}"
      append_tags: True
      tags:
        env: "{{ tagbdlab07 }}" 
  
  - name: Update NSG - Enable 80 port
    azure_rm_securitygroup:
      resource_group: "{{ rgr }}"
      name: "{{ nsglab07 }}"
      rules:
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1003
          direction: Inbound
