- hosts: [webservers]
  become: yes
  become_method: sudo
  tasks:
    - include_role:
        name: webapache
    - include_role:
        name: copyfiles

- hosts: [bds]
  become: yes
  become_method: sudo
  tasks:
    - include_role:
        name: installmysql
    - include_role:
        name: confmysql
    - include_role:
        name: importbd